import React from "react";

const data = [
  [
    "Luke Skywalker",
    "Darth Vader",
    "Leia organa ",
    "Owen Lars",
    "Beru Whitesun Lars",
    "Biggs Darklighter",
    "Obi-wan Kenobi",
    "Anakin Skywalker",
    "Han Solo",
    "Wedge Antilles",
    "Jek Tono Porkins",
    "Palpatine",
    "Boba Fett",
    "Lando Calrissian",
    "Lobot",
    "Mon Mothma",
    "Arvel Crynyd",
    "Finis Valorum",
    "Ric Olié",
    "Quarsh Panaka",
    "Shmi Skywalker",
    "Mace Windu",
    "Gregar Typho",
    "Cordé",
    "Cliegg Lars",
    "Dormé",
    "Bail Prestor Organa",
    "Jango Fett",
    "Jocasta Nu",
    "Raymus Antilles",
  ],
  ["C-3PO", "R2-D2", "R5-D4", "IG-88", "Grievous", "R4-P17"],
  ["Chewbacca", "Tarfful"],
  ["Greedo"],
  ["Jabba Desilijic Tiure", "Dooku"],
  ["Yoda"],
  ["Bossk"],
  ["Ackbar"],
  ["Wicket Systri Warrick"],
  [
    "Nute Gunray",
    "Jar Jar Binks",
    "Roos Tarpals",
    "Rugor Nass",
    "Watto",
    "Sebulba",
    "Darth Maul",
    "Bib Fortuna",
    "Ratts Tyerel",
    "Gasgano",
  ],
];

export default data;
